version: '3.8'

services:
  lgy-web:
    build: .
    container_name: lgy_web_container
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

